export const ERROR_CODE = {
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  NOT_FOUND: 'NOT_FOUND',
  DATA_REQUEST_INVALID_FORMAT: 'DATA_REQUEST_INVALID_FORMAT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};
